FROM node:22-alpine AS base

WORKDIR /app

COPY package.json ./
COPY packages ./packages
COPY apps/web ./apps/web

RUN npm install
RUN npm run build --workspace=@campus-os/shared-types
RUN npm run build --workspace=@campus-os/config
RUN npm run build --workspace=@campus-os/validation
WORKDIR /app/apps/web
RUN npm run build

EXPOSE 3000

ENV NODE_ENV=production
CMD ["npm", "start"]
